language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dmirlin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dmirlin/docker-react yarn run test